### ISSUE TITLE
I can sign in the juci

### ISSUE THREAD

**Issue by erniusias** [mkschreder/luci-express#5]
I just look the sign in page, after sign in , the
sid is always “RPC_DEFAULT_SESSION_ID”.  And I get this log "WARNING: JUCI.module() is deprecated! [core]"

**Comment by mkschreder** [comment]
When you run from box or using juci-local-server?

**Comment by erniusias** [comment]
Using juci-local-server, and I remove /usr/libexec/rpcd/juci-ubus-core-cgi since it block rpcd deamon

**Comment by mkschreder** [comment]
That's because you are using old version of rpcd. I have patched it so it
loads shared libs correctly (only .so files, not programs). You can get it
from https://github.com/mkschreder/juci-rpcd

You may also want to get https://github.com/mkschreder/juci-uhttpd with
some fixes there as well. For a complete list of packages that have correct
version you can get https://github.com/mkschreder/juci-feed and just run
make and it will download all of them.

**Comment by mkschreder** [comment]
The side effect of removing cgi program is that upgrade and config backup
will not work in webgui.

**Comment by erniusias** [comment]
Thanks，I test juci backend on real openwrt router. Forward the ubus request to router with juci-local-server. So I use the juci-core from  juci-openwrt-feed. I can see the session login request is ok, But it  return to the sign in page.

**Comment by mkschreder** [comment]
It is once again because you have their rpcd. It has to do with session
access call not returning same info as login call. The access call should
return your currently logged in user. If it doesn't find that info it will
log you out and go back to login page.

**Comment by erniusias** [comment]
Thanks for your replay, I replaced the procd with juci-procd, this problem is solved. others I install the questd, then I can arrive at overview page, but I get a large amount of error log. I think I need more js and angular.js knowledge.

**Comment by mkschreder** [comment]
Well you should install all dependencies from the juci feed. But you should
take them from iopsys (it is a fork of openwrt that we use on all our
routers) juci is an iopsys project so naturally there can be things
missing. But already there are only a few minor things. before it was much
more.

**Comment by erniusias** [comment]
Thanks, I got the page after when switch the theme form vodafone to juci-inteno.
